In [ ]:
from __future__ import print_function
import cv2 as cv
import numpy as np
import argparse
import random as rng
source_window = 'Image'
maxTrackbar = 25
rng.seed(12345)


'''
parser = argparse.ArgumentParser(description='Argparse Tutorial')
# argument는 원하는 만큼 추가한다.
parser.add_argument('--print-number', type=int, 
                    help='an integer for printing repeatably')

args = parser.parse_args(args=[])


일단 ArgumentParser에 원하는 description을 입력하여 parser 객체를 생성한다. description 외에도 usage, default value 등을 지정할 수 있다.
그리고 add_argument() method를 통해 원하는 만큼 인자 종류를 추가한다.
parse_args() method로 명령창에서 주어진 인자를 파싱한다.
args라는 이름으로 파싱을 성공했다면 args.parameter 형태로 주어진 인자 값을 받아 사용할 수 있다.
'''

def FindingCorner(val):
    maxCorners = max(val, 1)
    # Parameters for Shi-Tomasi algorithm
    qualityLevel = 0.01
    minDistance = 10
    blockSize = 3
    gradientSize = 3
    useHarrisDetector = False
    k = 0.04
    # Copy the source image
    copy = np.copy(src)
    
    # Apply corner detection
    corners = cv.goodFeaturesToTrack(src_gray, maxCorners, qualityLevel, minDistance, None, \
        blockSize=blockSize, gradientSize=gradientSize, useHarrisDetector=useHarrisDetector, k=k)
    
    # Draw corners detected
    print('** Number of corners detected:', corners.shape[0])
    radius = 4

    for i in range(corners.shape[0]):
        cv.circle(copy, (int(corners[i,0,0]), int(corners[i,0,1])), radius, (rng.randint(0,256), rng.randint(0,256), rng.randint(0,256)), cv.FILLED)
    
    # Show what you got
    cv.namedWindow(source_window)
    cv.imshow(source_window, copy)
    
    # Set the needed parameters to find the refined corners
    winSize = (5, 5)
    zeroZone = (-1, -1)
    criteria = (cv.TERM_CRITERIA_EPS + cv.TermCriteria_COUNT, 40, 0.001)
    
    # Calculate the refined corner locations
    corners = cv.cornerSubPix(src_gray, corners, winSize, zeroZone, criteria)
    for i in range(corners.shape[0]):
        print(" -- Refined Corner [", i, "]  (", corners[i,0,0], ",", corners[i,0,1], ")")
        print(type(corners))
        print(corners[1])
        print(corners[2])

# Load source image and convert it to gray
parser = argparse.ArgumentParser(description='Code for Shi-Tomasi corner detector tutorial.')
parser.add_argument('--input', help='Path to input image.', default='./camera calibration source/2.jpg')
args = parser.parse_args(args=[])
src = cv.imread(cv.samples.findFile(args.input))

if src is None:
    print('Could not open or find the image:', args.input)
    exit(0)

src_gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)

# Create a window and a trackbar
cv.namedWindow(source_window)
maxCorners = 10 #threshold
cv.createTrackbar('Threshold: ', source_window, maxCorners, maxTrackbar, goodFeaturesToTrack_Demo)
cv.imshow(source_window, src)
FindingCorner(maxCorners)

cv.waitKey()

** Number of corners detected: 10
 -- Refined Corner [ 0 ]  ( 710.29553 , 437.39334 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 1 ]  ( 719.72394 , 608.60547 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 2 ]  ( 94.54508 , 493.97333 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 3 ]  ( 922.9541 , 594.588 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 4 ]  ( 896.1963 , 420.9372 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 5 ]  ( 706.46484 , 362.11093 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 6 ]  ( 532.9526 , 453.64447 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.54508 493.97333]]
 -- Refined Corner [ 7 ]  ( 863.5186 , 208.73257 )
<class 'numpy.ndarray'>
[[719.72394 608.60547]]
[[ 94.

210810

좌표가 나오도록 하긴 했으나, 왼쪽 위가 (0, 0)인 2D 사진상의 좌표만 나오며
원점을 찾고, 한칸이 1이 되도록 수정 必 -> 어떻게?

idea

좌표 -> 점 하나가 카운트될 때마다 1씩 증가,
가로 세로 최대 갯수로 사이즈 가늠하고
원점 찾기 -> 어떻게?

일단 원점을 '체스판의' 왼쪽 위로 본다면, 점이 처음 발견되는 곳을 원점으로 설정

In [ ]:
def CoordinateCorners(beforeCorner, afterCorner, distance_x, distance_y) :
    (distance_x, distance_y) = (10, 10)
        
    #initialize
    x, y = 0, 0
    afterCorner[0] = (0, 0)
    
    for i in range(maxCorners)
        if afterCorner[i, 0] - beforeCorner[i, 0] != 10 : # [i, 0] : i번째의 x좌표
            distance_x = afterCorner[i, 0] - beforeCorner[0, 0]
        elif afterCorner[i, 1] - beforeCorner[i, 1] != 10 : # [i, 1] : i번째의 y좌표
            distance_y = afterCorner[i, 1] - beforeCorner[0, 1]
    
            
    
        
    